spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/localdatabase?&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

server:
  port: 8082

my:
  name: angaolang
  age: 22
  number:  ${random.int}
  uuid: ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${my.name}

